# Generated by Django 5.1 on 2024-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("family", "Family"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "room_preference",
                    models.CharField(
                        choices=[("with_ac", "With AC"), ("without_ac", "Without AC")],
                        max_length=10,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
            ],
        ),
    ]
